version: "3.8"

services:
  mindbot: 
    container_name: mindbot
    image: mindbot:latest
    build:
      context: .
    volumes:
      - type: bind
        source: ./token.txt
        target: /mindbot/token.txt
      - type: bind
        source: ./uploaded_assets/
        target: /data/uploaded_assets/
      - type: bind
        source: ./card_outputs/
        target: /data/card_outputs/
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
      ASSETS_UPLOAD_FOLDER: /data/uploaded_assets
      CARD_OUTPUT_FOLDER: /data/card_outputs
    depends_on: 
      - carddatabase


  carddatabase:
    image : mongo
    container_name: mongodb
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped